---
# tasks file for marathon
- name: Install marathon package
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - marathon={{ marathon_pkg_version }}
  sudo: yes
  when: marathon_install_type == "package" and marathon_only == False

- name: Install marathon and mesos packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - mesos={{ mesos_pkg_version }}
    - marathon={{ marathon_pkg_version }}
  sudo: yes
  when: marathon_install_type == "package" and marathon_only == True

# Disable Mesos Master, Mesos Slave, and ZooKeeper services
# As of Sep 2014 there is a hard dependency on libmesos for the native half
# of the JNI Mesos bindings. As a result, the mesos package must be installed
# even on a host that is only running Marathon. This may change in the future.
- name: Disable the Mesos Master service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override
    mode: 0644
  sudo: yes
  when: marathon_install_type == "package" and marathon_only == True

- name: Disable the Mesos Slave service
  copy:
    content: "manual"
    dest: /etc/init/mesos-slave.override
    mode: 0644
  sudo: yes
  when: marathon_install_type == "package" and marathon_only == True

- name: Disable the ZooKeeper service
  copy:
    content: "manual"
    dest: /etc/init/zookeeper.override
    mode: 0644
  sudo: yes
  notify:
    - Stop zookeeper
  when: marathon_install_type == "package" and marathon_only == True

  # Used for Marathon to locate the ZooKeeper(s) and Mesos Master(s)
- name: Set ZooKeeper URL
  copy:
    content: "{{zookeeper_url}}"
    dest: /etc/mesos/zk
    mode: 0644
  sudo: yes
  when: marathon_install_type == "package" and marathon_only == True

- name: Create Marathon Upstart job for packaged version
  template: src=marathon.conf.j2 dest=/etc/init/marathon.conf
  sudo: yes
  notify:
    - Restart marathon
  when: marathon_install_type == "package"
