---
# handlers file for marathon

# Restart service marathon, in all cases
- name: Restart marathon
  service: name=marathon state=restarted
  sudo: yes

- name: Stop zookeeper
  shell: stop zookeeper
  sudo: yes
